/*
 * This file is auto-generated. Modifications will be lost.
 *
 * See https://android.googlesource.com/platform/bionic/+/master/libc/kernel/
 * for more information.
 */
#ifndef _LINUX_VIRTIO_IDS_H
#define _LINUX_VIRTIO_IDS_H
#define VIRTIO_ID_NET 1
#define VIRTIO_ID_BLOCK 2
#define VIRTIO_ID_CONSOLE 3
#define VIRTIO_ID_RNG 4
#define VIRTIO_ID_BALLOON 5
#define VIRTIO_ID_IOMEM 6
#define VIRTIO_ID_RPMSG 7
#define VIRTIO_ID_SCSI 8
#define VIRTIO_ID_9P 9
#define VIRTIO_ID_MAC80211_WLAN 10
#define VIRTIO_ID_RPROC_SERIAL 11
#define VIRTIO_ID_CAIF 12
#define VIRTIO_ID_MEMORY_BALLOON 13
#define VIRTIO_ID_GPU 16
#define VIRTIO_ID_CLOCK 17
#define VIRTIO_ID_INPUT 18
#define VIRTIO_ID_VSOCK 19
#define VIRTIO_ID_CRYPTO 20
#define VIRTIO_ID_SIGNAL_DIST 21
#define VIRTIO_ID_PSTORE 22
#define VIRTIO_ID_IOMMU 23
#define VIRTIO_ID_MEM 24
#define VIRTIO_ID_SOUND 25
#define VIRTIO_ID_FS 26
#define VIRTIO_ID_PMEM 27
#define VIRTIO_ID_RPMB 28
#define VIRTIO_ID_MAC80211_HWSIM 29
#define VIRTIO_ID_VIDEO_ENCODER 30
#define VIRTIO_ID_VIDEO_DECODER 31
#define VIRTIO_ID_SCMI 32
#define VIRTIO_ID_NITRO_SEC_MOD 33
#define VIRTIO_ID_I2C_ADAPTER 34
#define VIRTIO_ID_WATCHDOG 35
#define VIRTIO_ID_CAN 36
#define VIRTIO_ID_DMABUF 37
#define VIRTIO_ID_PARAM_SERV 38
#define VIRTIO_ID_AUDIO_POLICY 39
#define VIRTIO_ID_BT 40
#define VIRTIO_ID_GPIO 41
#define VIRTIO_TRANS_ID_NET 0x1000
#define VIRTIO_TRANS_ID_BLOCK 0x1001
#define VIRTIO_TRANS_ID_BALLOON 0x1002
#define VIRTIO_TRANS_ID_CONSOLE 0x1003
#define VIRTIO_TRANS_ID_SCSI 0x1004
#define VIRTIO_TRANS_ID_RNG 0x1005
#define VIRTIO_TRANS_ID_9P 0x1009
#endif
