// Copyright (C) 2017 The Android Open Source Project
// SPDX-License-Identifier: BSD-2-Clause

#include <errno.h>

#include "header_checks.h"

static void errno_h() {
  int error = errno;

  MACRO(E2BIG);
  MACRO(EACCES);
  MACRO(EADDRINUSE);
  MACRO(EADDRNOTAVAIL);
  MACRO(EAFNOSUPPORT);
  MACRO(EAGAIN);
  MACRO(EALREADY);
  MACRO(EBADF);
  MACRO(EBADMSG);
  MACRO(EBUSY);
  MACRO(ECANCELED);
  MACRO(ECHILD);
  MACRO(ECONNABORTED);
  MACRO(ECONNRESET);
  MACRO(EDEADLK);
  MACRO(EDESTADDRREQ);
  MACRO(EDOM);
  MACRO(EDQUOT);
  MACRO(EEXIST);
  MACRO(EFAULT);
  MACRO(EFBIG);
  MACRO(EHOSTUNREACH);
  MACRO(EIDRM);
  MACRO(EILSEQ);
  MACRO(EINPROGRESS);
  MACRO(EINTR);
  MACRO(EINVAL);
  MACRO(EIO);
  MACRO(EISCONN);
  MACRO(EISDIR);
  MACRO(ELOOP);
  MACRO(EMFILE);
  MACRO(EMLINK);
  MACRO(EMSGSIZE);
  MACRO(EMULTIHOP);
  MACRO(ENAMETOOLONG);
  MACRO(ENETDOWN);
  MACRO(ENETRESET);
  MACRO(ENETUNREACH);
  MACRO(ENFILE);
  MACRO(ENOBUFS);
  MACRO(ENODATA);
  MACRO(ENODEV);
  MACRO(ENOENT);
  MACRO(ENOEXEC);
  MACRO(ENOLCK);
  MACRO(ENOLINK);
  MACRO(ENOMEM);
  MACRO(ENOMSG);
  MACRO(ENOPROTOOPT);
  MACRO(ENOSPC);
  MACRO(ENOSR);
  MACRO(ENOSTR);
  MACRO(ENOSYS);
  MACRO(ENOTCONN);
  MACRO(ENOTDIR);
  MACRO(ENOTEMPTY);
  MACRO(ENOTRECOVERABLE);
  MACRO(ENOTSOCK);
  MACRO(ENOTSUP);
  MACRO(ENOTTY);
  MACRO(ENXIO);
  MACRO(EOPNOTSUPP);
  MACRO(EOVERFLOW);
  MACRO(EOWNERDEAD);
  MACRO(EPERM);
  MACRO(EPIPE);
  MACRO(EPROTO);
  MACRO(EPROTONOSUPPORT);
  MACRO(EPROTOTYPE);
  MACRO(ERANGE);
  MACRO(EROFS);
  MACRO(ESPIPE);
  MACRO(ESRCH);
  MACRO(ESTALE);
  MACRO(ETIME);
  MACRO(ETIMEDOUT);
  MACRO(ETXTBSY);
  MACRO(EWOULDBLOCK);
  MACRO(EXDEV);
}
