/*
 * Copyright (C) 2017 The Android Open Source Project
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

  MACRO(S_IFMT);
  MACRO(S_IFBLK);
  MACRO(S_IFCHR);
  MACRO(S_IFIFO);
  MACRO(S_IFREG);
  MACRO(S_IFDIR);
  MACRO(S_IFLNK);
  MACRO(S_IFSOCK);

  MACRO_VALUE(S_IRWXU, 0700);
  MACRO_VALUE(S_IRUSR, 0400);
  MACRO_VALUE(S_IWUSR, 0200);
  MACRO_VALUE(S_IXUSR, 0100);

  MACRO_VALUE(S_IRWXG, 070);
  MACRO_VALUE(S_IRGRP, 040);
  MACRO_VALUE(S_IWGRP, 020);
  MACRO_VALUE(S_IXGRP, 010);

  MACRO_VALUE(S_IRWXO, 07);
  MACRO_VALUE(S_IROTH, 04);
  MACRO_VALUE(S_IWOTH, 02);
  MACRO_VALUE(S_IXOTH, 01);

  MACRO_VALUE(S_ISUID, 04000);
  MACRO_VALUE(S_ISGID, 02000);
  MACRO_VALUE(S_ISVTX, 01000);
