// Copyright (C) 2017 The Android Open Source Project
// SPDX-License-Identifier: BSD-2-Clause

  MACRO(S_IFMT);
  MACRO(S_IFBLK);
  MACRO(S_IFCHR);
  MACRO(S_IFIFO);
  MACRO(S_IFREG);
  MACRO(S_IFDIR);
  MACRO(S_IFLNK);
  MACRO(S_IFSOCK);

  MACRO_VALUE(S_IRWXU, 0700);
  MACRO_VALUE(S_IRUSR, 0400);
  MACRO_VALUE(S_IWUSR, 0200);
  MACRO_VALUE(S_IXUSR, 0100);

  MACRO_VALUE(S_IRWXG, 070);
  MACRO_VALUE(S_IRGRP, 040);
  MACRO_VALUE(S_IWGRP, 020);
  MACRO_VALUE(S_IXGRP, 010);

  MACRO_VALUE(S_IRWXO, 07);
  MACRO_VALUE(S_IROTH, 04);
  MACRO_VALUE(S_IWOTH, 02);
  MACRO_VALUE(S_IXOTH, 01);

  MACRO_VALUE(S_ISUID, 04000);
  MACRO_VALUE(S_ISGID, 02000);
  MACRO_VALUE(S_ISVTX, 01000);
