// Copyright (C) 2017 The Android Open Source Project
// SPDX-License-Identifier: BSD-2-Clause

#include <tar.h>

#include "header_checks.h"

static void tar_h() {
  MACRO(TMAGIC);
  MACRO_VALUE(TMAGLEN, 6);
  MACRO(TVERSION);
  MACRO_VALUE(TVERSLEN, 2);

  MACRO_VALUE(REGTYPE, '0');
  MACRO_VALUE(AREGTYPE, '\0');
  MACRO_VALUE(LNKTYPE, '1');
  MACRO_VALUE(SYMTYPE, '2');
  MACRO_VALUE(CHRTYPE, '3');
  MACRO_VALUE(BLKTYPE, '4');
  MACRO_VALUE(DIRTYPE, '5');
  MACRO_VALUE(FIFOTYPE, '6');
  MACRO_VALUE(CONTTYPE, '7');

  MACRO_VALUE(TSUID, 04000);
  MACRO_VALUE(TSGID, 02000);
  MACRO_VALUE(TSVTX, 01000);
  MACRO_VALUE(TUREAD, 0400);
  MACRO_VALUE(TUWRITE, 0200);
  MACRO_VALUE(TUEXEC, 0100);
  MACRO_VALUE(TGREAD, 040);
  MACRO_VALUE(TGWRITE, 020);
  MACRO_VALUE(TGEXEC, 010);
  MACRO_VALUE(TOREAD, 04);
  MACRO_VALUE(TOWRITE, 02);
  MACRO_VALUE(TOEXEC, 01);
}
